# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- test_devops

variables:
# Azure Resource Manager connection created during pipeline creation
azureServiceConnectionId:'8097d5da-bc60-4b33-8e28-5e0792240e62'

webAppName:'testorion'

pool:
  vmImage: ubuntu-latest

steps:
    - task: UsePythonVersion@0
       inputs:
        versionSpec: '$(pythonVersion)'
        displayName: 'Use Python $(pythonVersion)'
    - script: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install setup
        pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
       workingDirectory: $(projectRoot)
       displayName: "Install requirements"

appendCommitMessageToRunName:
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
